/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.DefaultComboBoxModel;
import modelo.Materia;
import persistencia.MateriaData;

/**
 *
 * @author Mauricio
 */
public class AgregarMateria extends javax.swing.JInternalFrame {

    private final MateriaData materiaData;
    private DefaultComboBoxModel cmbModel = new DefaultComboBoxModel<>(new String[]{"Seleccione...","1 año", "2 año", "3 año", "4 año", "5 año"});

    /**
     * Creates new form AgregarMateria
     */
    public AgregarMateria(MateriaData materiaData) {
        this.materiaData = materiaData;
        initComponents();
        cmbAnioMateria.setModel(cmbModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombreMateria = new javax.swing.JLabel();
        lblAnioMateria = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbAnioMateria = new javax.swing.JComboBox<>();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Agregar Materia");

        lblNombreMateria.setText("Nombre:");

        lblAnioMateria.setText("Año:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cmbAnioMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAnioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnioMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAnioMateria)
                            .addComponent(lblNombreMateria))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitulo)
                            .addComponent(txtNombreMateria)
                            .addComponent(cmbAnioMateria, 0, 238, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMateria)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioMateria)
                    .addComponent(cmbAnioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            String nombre = txtNombreMateria.getText();
            Integer anio = cmbAnioMateria.getSelectedIndex();

            if (nombre.isEmpty() || nombre.isEmpty() || anio == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Complete el nombre de la materia y al año al que pertenece",
                        "Faltan datos", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Materia materia = new Materia();
            materia.setAnio(anio);
            materia.setNombre(nombre);
            materia.setEstado(true);

            boolean creada = materiaData.guardarMateria(materia);

            if (creada) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Materia " + materia.getNombre() + " creada con éxito.",
                        "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                limpiarFormulario();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se pudo crear la materia",
                        "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

     private void limpiarFormulario() {
        txtNombreMateria.setText("");
        cmbAnioMateria.setSelectedIndex(0);
        txtNombreMateria.requestFocus();
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbAnioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnioMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAnioMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbAnioMateria;
    private javax.swing.JLabel lblAnioMateria;
    private javax.swing.JLabel lblNombreMateria;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
