/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import persistencia.AlumnoData;

/**
 *
 * @author Mauricio
 */
public class VerAlumnos extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private AlumnoData alumnoData;

    /**
     * Creates new form VerAlumnos
     */
    public VerAlumnos(AlumnoData alumnoData) {
        this.alumnoData = alumnoData;
        initComponents();

        modeloTabla = (DefaultTableModel) tblLista.getModel();
        modeloTabla.setRowCount(0);
        tblLista.setModel(modeloTabla);
        llenarTabla();

        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2 && javax.swing.SwingUtilities.isLeftMouseButton(e)) {
                    int fila = tblLista.rowAtPoint(e.getPoint());
                    if (fila >= 0) {
                        String dniAlumno = (String) modeloTabla.getValueAt(fila, 1);
                        Alumno alumno = alumnoData.obtenerAlumnoPorDni(String.valueOf(dniAlumno));
                        DetalleAlumno detalle = new DetalleAlumno(alumno);
                        getDesktopPane().add(detalle);
                        int x = (getDesktopPane().getWidth() - detalle.getWidth()) / 2;
                        int y = (getDesktopPane().getHeight() - detalle.getHeight()) / 2;
                        detalle.setLocation(x, y);
                        detalle.setVisible(true);
                        detalle.toFront();
                    }
                }
            }
        });
    }

    private void llenarTabla() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        List<Alumno> alumnos = alumnoData.obtenerTodosLosAlumnos();
        modeloTabla.setRowCount(0);
        for (Alumno a : alumnos) {
            modeloTabla.addRow(new Object[]{
                a.getIdAlumno(),
                a.getDni(),
                a.getApellido(),
                a.getNombre(),
                a.getFechaNacimiento().format(formatter),
                a.getEstado() ? "Activo" : "Inactivo"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        scrLista = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        btnDetalle = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Alumnos");

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Apellido", "Nombre", "Fecha de nacimiento", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrLista.setViewportView(tblLista);

        btnDetalle.setText("Detalle");
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(335, 335, 335)
                            .addComponent(lblTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(scrLista, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(338, 338, 338)
                            .addComponent(btnDetalle))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addComponent(scrLista, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        // TODO add your handling code here:
        int fila = tblLista.getSelectedRow();
        if (fila >= 0) {
            String dniAlumno = (String) modeloTabla.getValueAt(fila, 1);
            Alumno alumno = alumnoData.obtenerAlumnoPorDni(String.valueOf(dniAlumno));
            DetalleAlumno detalle = new DetalleAlumno(alumno);
            getDesktopPane().add(detalle);
            int x = (getDesktopPane().getWidth() - detalle.getWidth()) / 2;
            int y = (getDesktopPane().getHeight() - detalle.getHeight()) / 2;
            detalle.setLocation(x, y);
            detalle.setVisible(true);
            detalle.toFront();
        }
    }//GEN-LAST:event_btnDetalleActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDetalle;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrLista;
    private javax.swing.JTable tblLista;
    // End of variables declaration//GEN-END:variables
}
