/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import javax.swing.JInternalFrame;
import persistance.AlumnoData;
import persistance.DbConnection;

/**
 *
 * @author Mauricio
 */
public class Main extends javax.swing.JFrame {

    private static DbConnection connection;
    private final AlumnoData alumnoData;
    
    
    /**
     * Creates new form Main
     */
    public Main() {
        connection = new DbConnection("jdbc:mariadb://localhost/universidad_gp13", "root", ""); 
        alumnoData = new AlumnoData(connection);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        mnbMenu = new javax.swing.JMenuBar();
        mnuAlumno = new javax.swing.JMenu();
        mniAagregar = new javax.swing.JMenuItem();
        mniBaja = new javax.swing.JMenuItem();
        mniAlta = new javax.swing.JMenuItem();
        mniBorrar = new javax.swing.JMenuItem();
        mnuBuscar = new javax.swing.JMenu();
        mniAlumnos = new javax.swing.JMenuItem();
        mniMaterias = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        mnuAlumno.setText("Alumno");

        mniAagregar.setText("Agregar Alumno");
        mniAagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAagregarActionPerformed(evt);
            }
        });
        mnuAlumno.add(mniAagregar);

        mniBaja.setText("Dar de Baja");
        mniBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBajaActionPerformed(evt);
            }
        });
        mnuAlumno.add(mniBaja);

        mniAlta.setText("Dar de Alta");
        mniAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAltaActionPerformed(evt);
            }
        });
        mnuAlumno.add(mniAlta);

        mniBorrar.setText("Borrar Alumno");
        mniBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBorrarActionPerformed(evt);
            }
        });
        mnuAlumno.add(mniBorrar);

        mnbMenu.add(mnuAlumno);

        mnuBuscar.setText("Buscar");

        mniAlumnos.setText("Alumnos");
        mniAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlumnosActionPerformed(evt);
            }
        });
        mnuBuscar.add(mniAlumnos);

        mniMaterias.setText("Materias");
        mnuBuscar.add(mniMaterias);

        mnbMenu.add(mnuBuscar);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mniSalir);

        mnbMenu.add(mnuSalir);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        int resp = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que quiere salir?",
            "Salir",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (resp == javax.swing.JOptionPane.YES_OPTION) {
            dispose();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBorrarActionPerformed
        // TODO add your handling code here:
        BorrarAlumno borrar = new BorrarAlumno();
        abrirYCentrar(borrar);
    }//GEN-LAST:event_mniBorrarActionPerformed

    private void mniAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlumnosActionPerformed
        // TODO add your handling code here:
        BuscarAlumno buscar = new BuscarAlumno(alumnoData);
        abrirYCentrar(buscar);
    }//GEN-LAST:event_mniAlumnosActionPerformed

    private void mniAagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAagregarActionPerformed
        // TODO add your handling code here:
        AgregarAlumno agregar = new AgregarAlumno();
        abrirYCentrar(agregar);
    }//GEN-LAST:event_mniAagregarActionPerformed

    private void mniBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBajaActionPerformed
        // TODO add your handling code here:
        DarDeBaja baja = new DarDeBaja();
        abrirYCentrar(baja);
    }//GEN-LAST:event_mniBajaActionPerformed

    private void mniAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAltaActionPerformed
        // TODO add your handling code here:
        DarDeAlta alta = new DarDeAlta();
        abrirYCentrar(alta);
    }//GEN-LAST:event_mniAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */ 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void abrirYCentrar(JInternalFrame frame) {
        escritorio.add(frame);
        frame.pack(); 
        frame.setVisible(true);

        int x = (escritorio.getWidth() - frame.getWidth()) / 2;
        int y = (escritorio.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniAagregar;
    private javax.swing.JMenuItem mniAlta;
    private javax.swing.JMenuItem mniAlumnos;
    private javax.swing.JMenuItem mniBaja;
    private javax.swing.JMenuItem mniBorrar;
    private javax.swing.JMenuItem mniMaterias;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuAlumno;
    private javax.swing.JMenu mnuBuscar;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
